package pl.bitforge.domofon

import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.graphics.Bitmap
import android.os.Build
import android.os.Bundle
import android.util.Log
import android.view.Gravity
import android.view.ViewGroup
import android.widget.FrameLayout
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.core.view.WindowInsetsControllerCompat
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.lifecycleScope
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.launchIn
import kotlinx.coroutines.flow.onEach
import org.qtproject.example.domofon.DomofonQml.Main
import org.qtproject.qt.android.QtQmlStatus
import org.qtproject.qt.android.QtQmlStatusChangeListener
import org.qtproject.qt.android.QtQuickView
import org.qtproject.qt.android.QtQuickViewContent
import pl.bitforge.domofon.camera.CameraFrameGrabber
import pl.bitforge.domofon.config.ConfigStore
import pl.bitforge.domofon.config.SettingsActivity
import pl.bitforge.domofon.gate.GateNotifier
import pl.bitforge.domofon.gate.GateRepository
import pl.bitforge.domofon.gate.gateStatusLine
import pl.bitforge.domofon.geo.GeofenceManager
import pl.bitforge.domofon.geo.HomeDistanceTracker
import pl.bitforge.domofon.geo.formatHomeDistance
import java.io.File

/**
 * Hosts the QML UI inside a normal Kotlin activity via [QtQuickView].
 *
 * [Main] is generated by the Qt Gradle Plugin from qtquickview/Main.qml. Its package is
 * org.qtproject.example.<cmake target>.<qml module URI> — change either in
 * qtquickview/CMakeLists.txt and this import must change with it.
 */
class MainActivity : AppCompatActivity(), QtQmlStatusChangeListener {

    private val mainQml = Main()
    private var commandListenerId = 0
    private var settingsListenerId = 0

    /** Wraps the Qt view; also the handler the QML-load watchdog is posted on. */
    private lateinit var container: FrameLayout

    /**
     * Produces camera stills. applicationContext, not `this`: it is held for the activity's
     * whole life and outlives configuration changes, so an activity context here would leak.
     * Started/stopped with the activity, like the MQTT connection.
     */
    private val cameraGrabber by lazy { CameraFrameGrabber(applicationContext) }

    /**
     * Live distance to the home geofence centre. applicationContext for the same reason as
     * [cameraGrabber]. Runs only while the activity is started; it stays silent unless the
     * geofence feature is on and located, so most installs never see it.
     */
    private val homeDistanceTracker by lazy { HomeDistanceTracker(applicationContext) }

    /** Bumped per frame; its parity picks the cache file, so the URL alternates. See [writeFrame]. */
    private var frameVersion = 0

    /** Setting a QML property before the view reports READY is a no-op at best. */
    @Volatile
    private var qmlReady = false

    /** True until the first READY of a fresh launch has decided about the setup redirect. */
    private var firstRun = false

    /**
     * False when [onCreate] bailed out before building any UI, because this process has
     * already hosted Qt. Such an instance is a placeholder waiting for a fresh process: it
     * owns no view, no MQTT connection and no camera grabber, so every other callback has
     * to leave it alone.
     */
    private var hostingQt = true

    /**
     * Fires if [onStatusChanged] has not reported READY well after [QtQuickView.loadContent].
     * A `QtQuickView` stopped mid-load stalls forever — it does not resume when the activity
     * comes back — and the only cure is a new process, so this is the same exit as the
     * second-activity guard in [onCreate].
     */
    private val qmlWatchdog = Runnable {
        if (qmlReady) return@Runnable
        // Restarting from the background would be both rude and, under targetSdk 36's
        // background-activity-launch rules, likely to be dropped on the floor.
        if (!lifecycle.currentState.isAtLeast(Lifecycle.State.STARTED)) return@Runnable
        Log.w(TAG, "QML never reported READY — restarting into a fresh process")
        if (!QtRestartActivity.restart(this)) showRestartFallback()
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // Qt is one QGuiApplication per process, owned by the activity that first loaded it.
        // A second MainActivity in the same process gets a QtQuickView that renders nothing,
        // and usually takes the process down first — "JNI DETECTED ERROR IN APPLICATION:
        // java_class == null ... from QtNative.runPendingCppRunnables()", a SIGABRT out of
        // Qt's stale JNI class cache. Normally the process dies with the task and the second
        // activity never happens; a bound car session (DomofonCarAppService) keeps the
        // process alive for the whole drive, which turns "swipe the app away and reopen it"
        // into exactly this. So hand the launch to a fresh process instead of loading Qt
        // twice. See docs/10-troubleshooting.md, Android Auto section.
        if (qtHostedInThisProcess) {
            Log.w(TAG, "Qt already hosted in this process — restarting into a fresh one")
            hostingQt = false
            if (!QtRestartActivity.restart(this)) showRestartFallback()
            return
        }
        qtHostedInThisProcess = true

        val qtQuickView = QtQuickView(this)

        // Tapjacking guard. minSdk is 28, and the platform only started blocking obscured
        // touches itself in Android 12 — before that, an app holding SYSTEM_ALERT_WINDOW
        // could launch this (exported) activity and float a decoy over the Open button,
        // whose position is trivially predictable from the QML layout.
        qtQuickView.filterTouchesWhenObscured = true
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) window.setHideOverlayWindows(true)

        // targetSdk 36 enforces edge-to-edge: the window draws behind the status and
        // navigation bars, and without this the QML settings gear sits under the clock.
        // The QML view is padded away from the bars via a wrapper whose background matches
        // the QML root color, so the bar areas read as part of the scene instead of as a
        // differently-coloured strip.
        container = FrameLayout(this).apply {
            setBackgroundColor(QML_BACKGROUND) // keep in sync with Main.qml root color
            addView(
                qtQuickView,
                ViewGroup.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.MATCH_PARENT,
                ),
            )
        }
        ViewCompat.setOnApplyWindowInsetsListener(container) { v, insets ->
            val bars = insets.getInsets(
                WindowInsetsCompat.Type.systemBars() or WindowInsetsCompat.Type.displayCutout()
            )
            v.setPadding(bars.left, bars.top, bars.right, bars.bottom)
            WindowInsetsCompat.CONSUMED
        }
        // The scene is dark regardless of the system theme, so the bar icons must be light
        // regardless of the system theme too.
        WindowInsetsControllerCompat(window, window.decorView).apply {
            isAppearanceLightStatusBars = false
            isAppearanceLightNavigationBars = false
        }

        setContentView(
            container,
            ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT,
            ),
        )

        mainQml.setStatusChangeListener(this)
        qtQuickView.loadContent(mainQml)
        container.postDelayed(qmlWatchdog, QML_READY_TIMEOUT_MS)

        // Kotlin -> QML: one status line, derived in the backend so the phone and the car
        // word it identically (see gateStatusLine). Combined from the three flows that feed
        // it — our own socket, the bridge, and the gate state — so a change in any one
        // recomputes the single line the QML renders verbatim.
        combine(
            GateRepository.gateState,
            GateRepository.bridgeStatus,
            GateRepository.connection,
        ) { gs, bridge, conn -> gateStatusLine(conn, bridge, gs.state) }
            .onEach { if (qmlReady) mainQml.statusText = it }
            .launchIn(lifecycleScope)

        // Why the last command did not reach the gate. Distinct from the connection reason
        // folded into the status line: the socket can be perfectly healthy and the command
        // still be refused by the bridge, so this stays its own line.
        GateRepository.lastError
            .onEach { if (qmlReady) mainQml.lastError = it }
            .launchIn(lifecycleScope)

        // A new still: persist it and hand QML a fresh URL. A Bitmap cannot cross the
        // QtQuickView property bridge, so the frame travels as a file the Image loads.
        cameraGrabber.frame
            .onEach { bitmap -> if (qmlReady && bitmap != null) mainQml.cameraFrame = writeFrame(bitmap) }
            .launchIn(lifecycleScope)

        cameraGrabber.status
            .onEach { if (qmlReady) mainQml.cameraStatus = it.name.lowercase() }
            .launchIn(lifecycleScope)

        // Whether a camera is configured at all decides if the QML panel appears. Driven off
        // config so entering the URL in Settings shows the panel without a relaunch.
        ConfigStore.config
            .onEach { if (qmlReady) mainQml.cameraConfigured = it.camera.hasPicture }
            .launchIn(lifecycleScope)

        // Distance to home. Empty string when the tracker has nothing, which hides the line.
        homeDistanceTracker.distance
            .onEach { if (qmlReady) mainQml.homeDistance = formatHomeDistance(it) }
            .launchIn(lifecycleScope)

        GateNotifier.observe(this, lifecycleScope)

        // First run goes straight to setup — but only from onStatusChanged, once the QML
        // reports READY. Launching Settings here would race the QML load: if Settings
        // covers this activity before the load completes, QtQuickView stalls mid-load and
        // never recovers, and backing out of Settings lands on a dead screen (see
        // docs/10-troubleshooting.md, blank-screen entry).
        firstRun = savedInstanceState == null
    }

    override fun onStart() {
        super.onStart()
        if (!hostingQt) return

        // The load can also stall because the activity was stopped mid-load (a launch with
        // the screen off does it). Coming back does not resume it, so re-arm the watchdog
        // for a window in which we are actually visible and allowed to start an activity.
        if (!qmlReady) {
            container.removeCallbacks(qmlWatchdog)
            container.postDelayed(qmlWatchdog, QML_READY_TIMEOUT_MS)
        }

        GateRepository.connect()
        cameraGrabber.start()
        // Settings may have changed while we were away — including the home position or
        // the geofence toggle.
        GeofenceManager.sync(this)
        // Re-evaluates the feature/permission guards, so enabling the geofence in Settings and
        // coming back starts the readout without a relaunch.
        homeDistanceTracker.start()
        maybeRequestNotifications()
    }

    override fun onStop() {
        if (!hostingQt) {
            super.onStop()
            return
        }
        container.removeCallbacks(qmlWatchdog)
        GateRepository.disconnect()
        cameraGrabber.stop()
        homeDistanceTracker.stop()
        super.onStop()
    }

    override fun onStatusChanged(status: QtQmlStatus?, content: QtQuickViewContent?) {
        Log.i(TAG, "QtQuickView status: $status")
        if (status != QtQmlStatus.READY || content != mainQml) return
        qmlReady = true
        container.removeCallbacks(qmlWatchdog)
        QtRestartActivity.clearRestartStamp(this)

        // Seed the view with the state we already have.
        mainQml.statusText = gateStatusLine(
            GateRepository.connection.value,
            GateRepository.bridgeStatus.value,
            GateRepository.gateState.value.state,
        )
        mainQml.lastError = GateRepository.lastError.value
        mainQml.cameraConfigured = ConfigStore.current.camera.hasPicture
        mainQml.cameraStatus = cameraGrabber.status.value.name.lowercase()
        cameraGrabber.frame.value?.let { mainQml.cameraFrame = writeFrame(it) }
        mainQml.homeDistance = formatHomeDistance(homeDistanceTracker.distance.value)

        // QML -> Kotlin: the generated connect<Signal>Listener returns an id you can use
        // to disconnect later. The first lambda argument is the signal name.
        commandListenerId = mainQml.connectCommandRequestedListener { _, action ->
            Log.i(TAG, "QML asked: $action")
            GateRepository.sendCommand(action)
        }

        // The theme is NoActionBar so the QML fills the screen; the way back into setup is
        // a control inside the QML itself rather than an options menu that cannot render.
        settingsListenerId = mainQml.connectSettingsRequestedListener { _, _ ->
            startActivity(Intent(this, SettingsActivity::class.java))
        }

        // The first-run setup redirect, deferred here from onCreate: the scene is loaded
        // now, so covering the activity can no longer strand the load. Cleared so a
        // re-emitted READY cannot re-open Settings over whatever the user is doing.
        if (firstRun && !ConfigStore.current.isComplete) {
            firstRun = false
            startActivity(Intent(this, SettingsActivity::class.java))
        }
    }

    /**
     * Writes the latest frame to a private cache file and returns a `file://` URL for QML.
     *
     * Two files, used alternately, rather than one path plus a `?v=` cache-buster. Both
     * schemes give QML a URL that differs from the last one — required, because setting an
     * identical string on a QML property emits no change and QtQuick caches Image sources
     * by URL — but only alternating names guarantee we are never *rewriting the file Qt's
     * loader thread is reading*, which can fail the load outright and leave the panel blank
     * until the next snapshot. The QML side loads into whichever Image is hidden and only
     * swaps once the decode is done, so the old still stays up meanwhile.
     *
     * The bitmap is already ≤960 px on its longest edge (downscaled in the grabber), so the
     * JPEG is a few tens of KB.
     */
    private fun writeFrame(bitmap: Bitmap): String {
        val file = File(cacheDir, "camera-frame-${++frameVersion % 2}.jpg")
        file.outputStream().use { bitmap.compress(Bitmap.CompressFormat.JPEG, 85, it) }
        return "file://${file.absolutePath}"
    }

    /**
     * Shown when the process cannot host Qt and a restart was already attempted moments ago
     * — i.e. the restart did not take, and doing it again would be a launch loop. A plain
     * Android view on purpose: the whole problem is that Qt cannot draw in this process.
     */
    private fun showRestartFallback() {
        Log.e(TAG, "No Qt UI in this process and a restart was just tried — showing the fallback")
        setContentView(
            TextView(this).apply {
                text = getString(R.string.qt_ui_needs_restart)
                gravity = Gravity.CENTER
                setBackgroundColor(QML_BACKGROUND)
                setTextColor(0xFFA6ADC8.toInt()) // Main.qml's muted grey
                setPadding(64, 64, 64, 64)
            }
        )
    }

    private fun granted(permission: String) =
        ContextCompat.checkSelfPermission(this, permission) == PackageManager.PERMISSION_GRANTED

    /**
     * Notifications only. Location is *not* requested here.
     *
     * The geofence is an opt-in feature now, so asking for location on first launch would
     * be asking for a permission the user has not asked for a feature for — which is both
     * rude and, per Play's location policy, a documented rejection reason. It is requested
     * from [requestLocationForGeofence], reached only by switching the feature on.
     */
    private fun maybeRequestNotifications() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) return
        if (granted(Manifest.permission.POST_NOTIFICATIONS)) return
        // Once per install: a third-party app can bounce this activity in a loop, and a
        // permission dialog on every onStart would be a nuisance vector.
        if (askedForNotifications) return
        askedForNotifications = true
        requestPermissions(arrayOf(Manifest.permission.POST_NOTIFICATIONS), REQ_NOTIFICATIONS)
    }

    private companion object {
        const val TAG = "Domofon"
        const val REQ_NOTIFICATIONS = 3

        /**
         * How long the QML load may take before the view is written off as stalled. A cold
         * start with dexopt and Qt library extraction measures well under a second on the
         * test phone, so this is generous by design: firing early costs a process restart.
         */
        const val QML_READY_TIMEOUT_MS = 4_000L

        /**
         * Process-scoped, deliberately never reset: Qt cannot be started twice in one
         * process, and once an activity has loaded it the only way back to a working UI is
         * a new process. Survives this activity's destruction, which is the whole point.
         */
        var qtHostedInThisProcess = false

        /** Main.qml's root `color: "#1e1e2e"`. Change one and you must change both. */
        val QML_BACKGROUND = 0xFF1E1E2E.toInt()

        /** Process-scoped: enough to stop a start-activity loop nagging the user. */
        var askedForNotifications = false
    }
}
