package pl.bitforge.domofon

import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.os.Build
import android.os.Bundle
import android.util.Log
import android.view.Gravity
import android.view.ViewGroup
import android.widget.FrameLayout
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.core.view.WindowInsetsControllerCompat
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.lifecycleScope
import org.qtproject.example.domofon.DomofonQml.Main
import org.qtproject.qt.android.QtQmlStatus
import org.qtproject.qt.android.QtQmlStatusChangeListener
import org.qtproject.qt.android.QtQuickView
import org.qtproject.qt.android.QtQuickViewContent
import pl.bitforge.domofon.ui.settings.SettingsActivity
import pl.bitforge.domofon.data.mqtt.ConnectionLease
import pl.bitforge.domofon.ui.phone.PhoneTheme
import pl.bitforge.domofon.ui.phone.QmlGateBinder

/**
 * Hosts the QML UI inside a normal Kotlin activity via [QtQuickView].
 *
 * [Main] is generated by the Qt Gradle Plugin from qtquickview/Main.qml. Its package is
 * org.qtproject.example.<cmake target>.<qml module URI> — change either in
 * qtquickview/CMakeLists.txt and this import must change with it.
 */
class MainActivity : AppCompatActivity(), QtQmlStatusChangeListener {

    private val mainQml = Main()

    /** Held from onStart to onStop — this activity's claim on the MQTT connection. */
    private var gateLease: ConnectionLease? = null

    /** Wraps the Qt view; also the handler the QML-load watchdog is posted on. */
    private lateinit var qtHost: FrameLayout

    /**
     * Produces camera stills (the factory hands it applicationContext, so nothing here
     * leaks the activity). Started/stopped with the activity, like the MQTT lease.
     */
    private val cameraGrabber by lazy { container.newCameraGrabber(this) }

    /**
     * Live distance to the home geofence centre. Runs only while the activity is started;
     * it stays silent unless the geofence feature is on and located, so most installs
     * never see it.
     */
    private val homeDistanceTracker by lazy { container.newHomeDistanceTracker(this) }

    /** Derives everything the UI renders; shared shape with the car screen. */
    private val viewModel by lazy {
        container.newGateViewModel(lifecycleScope, cameraGrabber, homeDistanceTracker)
    }

    /** The one writer of the QML surface; created in onCreate, closed in onDestroy. */
    private var binder: QmlGateBinder? = null

    /** True until the first READY of a fresh launch has decided about the setup redirect. */
    private var firstRun = false

    /**
     * False when [onCreate] bailed out before building any UI, because this process has
     * already hosted Qt. Such an instance is a placeholder waiting for a fresh process: it
     * owns no view, no MQTT connection and no camera grabber, so every other callback has
     * to leave it alone.
     */
    private var hostingQt = true

    /**
     * Fires if [onStatusChanged] has not reported READY well after [QtQuickView.loadContent].
     * A `QtQuickView` stopped mid-load stalls forever — it does not resume when the activity
     * comes back — and the only cure is a new process, so this is the same exit as the
     * second-activity guard in [onCreate].
     */
    private val qmlWatchdog = Runnable {
        if (binder?.ready == true) return@Runnable
        // Restarting from the background would be both rude and, under targetSdk 36's
        // background-activity-launch rules, likely to be dropped on the floor.
        if (!lifecycle.currentState.isAtLeast(Lifecycle.State.STARTED)) return@Runnable
        Log.w(TAG, "QML never reported READY — restarting into a fresh process")
        if (!QtRestartActivity.restart(this)) showRestartFallback()
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        // Qt is one QGuiApplication per process, owned by the activity that first loaded it.
        // A second MainActivity in the same process gets a QtQuickView that renders nothing,
        // and usually takes the process down first — "JNI DETECTED ERROR IN APPLICATION:
        // java_class == null ... from QtNative.runPendingCppRunnables()", a SIGABRT out of
        // Qt's stale JNI class cache. Normally the process dies with the task and the second
        // activity never happens; a bound car session (DomofonCarAppService) keeps the
        // process alive for the whole drive, which turns "swipe the app away and reopen it"
        // into exactly this. So hand the launch to a fresh process instead of loading Qt
        // twice. See docs/troubleshooting.md, Android Auto section.
        if (qtHostedInThisProcess) {
            Log.w(TAG, "Qt already hosted in this process — restarting into a fresh one")
            hostingQt = false
            if (!QtRestartActivity.restart(this)) showRestartFallback()
            return
        }
        qtHostedInThisProcess = true

        val qtQuickView = QtQuickView(this)

        // Tapjacking guard. minSdk is 28, and the platform only started blocking obscured
        // touches itself in Android 12 — before that, an app holding SYSTEM_ALERT_WINDOW
        // could launch this (exported) activity and float a decoy over the Open button,
        // whose position is trivially predictable from the QML layout.
        qtQuickView.filterTouchesWhenObscured = true
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) window.setHideOverlayWindows(true)

        // targetSdk 36 enforces edge-to-edge: the window draws behind the status and
        // navigation bars, and without this the QML settings gear sits under the clock.
        // The QML view is padded away from the bars via a wrapper whose background matches
        // the QML root color, so the bar areas read as part of the scene instead of as a
        // differently-coloured strip.
        qtHost = FrameLayout(this).apply {
            setBackgroundColor(PhoneTheme.BASE) // Theme.qml `base` — the QML root color
            addView(
                qtQuickView,
                ViewGroup.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.MATCH_PARENT,
                ),
            )
        }
        ViewCompat.setOnApplyWindowInsetsListener(qtHost) { v, insets ->
            val bars = insets.getInsets(
                WindowInsetsCompat.Type.systemBars() or WindowInsetsCompat.Type.displayCutout()
            )
            v.setPadding(bars.left, bars.top, bars.right, bars.bottom)
            WindowInsetsCompat.CONSUMED
        }
        // The scene is dark regardless of the system theme, so the bar icons must be light
        // regardless of the system theme too.
        WindowInsetsControllerCompat(window, window.decorView).apply {
            isAppearanceLightStatusBars = false
            isAppearanceLightNavigationBars = false
        }

        setContentView(
            qtHost,
            ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT,
            ),
        )

        // The binder is the single writer of the QML surface: it collects the ViewModel
        // while the scene is live and seeds it once on READY, through the same render()
        // path — this used to be six collectors plus a hand-maintained duplicate seed.
        //
        // Built *before* loadContent, along with the first-run flag below, because both are
        // read from onStatusChanged: the load is asynchronous in practice, but a READY
        // delivered synchronously from inside loadContent would otherwise find a null
        // binder — no seed, no signal listeners, dead buttons — and silently do nothing.
        binder = QmlGateBinder(
            mainQml = mainQml,
            viewModel = viewModel,
            scope = lifecycleScope,
            onSettingsRequested = { startActivity(Intent(this, SettingsActivity::class.java)) },
        )

        // First run goes straight to setup — but only from onStatusChanged, once the QML
        // reports READY. Launching Settings here would race the QML load: if Settings
        // covers this activity before the load completes, QtQuickView stalls mid-load and
        // never recovers, and backing out of Settings lands on a dead screen (see
        // docs/troubleshooting.md, blank-screen entry).
        firstRun = savedInstanceState == null

        mainQml.setStatusChangeListener(this)
        qtQuickView.loadContent(mainQml)
        qtHost.postDelayed(qmlWatchdog, QML_READY_TIMEOUT_MS)
    }

    override fun onStart() {
        super.onStart()
        if (!hostingQt) return

        // The load can also stall because the activity was stopped mid-load (a launch with
        // the screen off does it). Coming back does not resume it, so re-arm the watchdog
        // for a window in which we are actually visible and allowed to start an activity.
        if (binder?.ready != true) {
            qtHost.removeCallbacks(qmlWatchdog)
            qtHost.postDelayed(qmlWatchdog, QML_READY_TIMEOUT_MS)
        }

        gateLease = container.gateService.acquire("phone-ui")
        cameraGrabber.start()
        // Settings may have changed while we were away — including the home position or
        // the geofence toggle.
        container.geofenceManager.sync(this)
        // Re-evaluates the feature/permission guards, so enabling the geofence in Settings and
        // coming back starts the readout without a relaunch.
        homeDistanceTracker.start()
        // The gate screen is in front, so it is already showing every state a heads-up would
        // announce — and anything left in the shade is about to be contradicted by it.
        container.surfaces.phoneScreen(true)
        container.gateNotifier.clearTransient(this)
        maybeRequestNotifications()
    }

    override fun onStop() {
        // Unconditionally, and before every early return: a stuck "visible" would silence
        // every notification for the life of the process, which is the one failure this
        // suppression must not be able to cause.
        container.surfaces.phoneScreen(false)
        if (!hostingQt) {
            super.onStop()
            return
        }
        qtHost.removeCallbacks(qmlWatchdog)
        gateLease?.close()
        gateLease = null
        cameraGrabber.stop()
        homeDistanceTracker.stop()
        super.onStop()
    }

    override fun onStatusChanged(status: QtQmlStatus?, content: QtQuickViewContent?) {
        Log.i(TAG, "QtQuickView status: $status")
        if (status != QtQmlStatus.READY || content != mainQml) return
        qtHost.removeCallbacks(qmlWatchdog)
        QtRestartActivity.clearRestartStamp(this)

        // Seeds the scene and wires the QML -> Kotlin signals — see [QmlGateBinder].
        binder?.onQmlReady()

        // The first-run setup redirect, deferred here from onCreate: the scene is loaded
        // now, so covering the activity can no longer strand the load. Cleared so a
        // re-emitted READY cannot re-open Settings over whatever the user is doing.
        if (firstRun && !container.configStore.current.isComplete) {
            firstRun = false
            startActivity(Intent(this, SettingsActivity::class.java))
        }
    }

    override fun onDestroy() {
        // The signal listeners hold this activity through their lambdas on the Qt side;
        // the binder disconnects them and clears the frame cache.
        binder?.close()
        binder = null
        super.onDestroy()
    }

    /**
     * Shown when the process cannot host Qt and a restart was already attempted moments ago
     * — i.e. the restart did not take, and doing it again would be a launch loop. A plain
     * Android view on purpose: the whole problem is that Qt cannot draw in this process.
     */
    private fun showRestartFallback() {
        Log.e(TAG, "No Qt UI in this process and a restart was just tried — showing the fallback")
        setContentView(
            TextView(this).apply {
                text = getString(R.string.qt_ui_needs_restart)
                gravity = Gravity.CENTER
                setBackgroundColor(PhoneTheme.BASE)
                setTextColor(PhoneTheme.MUTED)
                setPadding(64, 64, 64, 64)
            }
        )
    }

    private fun granted(permission: String) =
        ContextCompat.checkSelfPermission(this, permission) == PackageManager.PERMISSION_GRANTED

    /**
     * Notifications only. Location is *not* requested here.
     *
     * The geofence is an opt-in feature now, so asking for location on first launch would
     * be asking for a permission the user has not asked for a feature for — which is both
     * rude and, per Play's location policy, a documented rejection reason. It is requested
     * from [requestLocationForGeofence], reached only by switching the feature on.
     */
    private fun maybeRequestNotifications() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) return
        if (granted(Manifest.permission.POST_NOTIFICATIONS)) return
        // Once per install: a third-party app can bounce this activity in a loop, and a
        // permission dialog on every onStart would be a nuisance vector.
        if (askedForNotifications) return
        askedForNotifications = true
        requestPermissions(arrayOf(Manifest.permission.POST_NOTIFICATIONS), REQ_NOTIFICATIONS)
    }

    private companion object {
        const val TAG = "Domofon"
        const val REQ_NOTIFICATIONS = 3

        /**
         * How long the QML load may take before the view is written off as stalled. A cold
         * start with dexopt and Qt library extraction measures well under a second on the
         * test phone, so this is generous by design: firing early costs a process restart.
         */
        const val QML_READY_TIMEOUT_MS = 4_000L

        /**
         * Process-scoped, deliberately never reset: Qt cannot be started twice in one
         * process, and once an activity has loaded it the only way back to a working UI is
         * a new process. Survives this activity's destruction, which is the whole point.
         */
        var qtHostedInThisProcess = false

        /** Process-scoped: enough to stop a start-activity loop nagging the user. */
        var askedForNotifications = false
    }
}
