package pl.bitforge.domofon

import android.Manifest
import android.content.Intent
import android.content.pm.PackageManager
import android.graphics.Bitmap
import android.os.Build
import android.os.Bundle
import android.util.Log
import android.view.ViewGroup
import android.widget.FrameLayout
import androidx.appcompat.app.AppCompatActivity
import androidx.core.content.ContextCompat
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.core.view.WindowInsetsControllerCompat
import androidx.lifecycle.lifecycleScope
import kotlinx.coroutines.flow.launchIn
import kotlinx.coroutines.flow.onEach
import org.qtproject.example.domofon.DomofonQml.Main
import org.qtproject.qt.android.QtQmlStatus
import org.qtproject.qt.android.QtQmlStatusChangeListener
import org.qtproject.qt.android.QtQuickView
import org.qtproject.qt.android.QtQuickViewContent
import pl.bitforge.domofon.camera.CameraFrameGrabber
import pl.bitforge.domofon.config.ConfigStore
import pl.bitforge.domofon.config.SettingsActivity
import pl.bitforge.domofon.gate.GateNotifier
import pl.bitforge.domofon.gate.GateRepository
import pl.bitforge.domofon.geo.GeofenceManager
import java.io.File

/**
 * Hosts the QML UI inside a normal Kotlin activity via [QtQuickView].
 *
 * [Main] is generated by the Qt Gradle Plugin from qtquickview/Main.qml. Its package is
 * org.qtproject.example.<cmake target>.<qml module URI> — change either in
 * qtquickview/CMakeLists.txt and this import must change with it.
 */
class MainActivity : AppCompatActivity(), QtQmlStatusChangeListener {

    private val mainQml = Main()
    private var commandListenerId = 0
    private var settingsListenerId = 0

    /**
     * Pulls camera stills over RTSP. applicationContext, not `this`: it is held for the
     * activity's whole life and outlives configuration changes, so an activity context here
     * would leak. Started/stopped with the activity, like the MQTT connection.
     */
    private val cameraGrabber by lazy { CameraFrameGrabber(applicationContext) }

    /** Bumped per frame so the QML Image URL changes and the view actually reloads. */
    private var frameVersion = 0

    /** Setting a QML property before the view reports READY is a no-op at best. */
    @Volatile
    private var qmlReady = false

    /** True until the first READY of a fresh launch has decided about the setup redirect. */
    private var firstRun = false

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        val qtQuickView = QtQuickView(this)

        // Tapjacking guard. minSdk is 28, and the platform only started blocking obscured
        // touches itself in Android 12 — before that, an app holding SYSTEM_ALERT_WINDOW
        // could launch this (exported) activity and float a decoy over the Open button,
        // whose position is trivially predictable from the QML layout.
        qtQuickView.filterTouchesWhenObscured = true
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) window.setHideOverlayWindows(true)

        // targetSdk 36 enforces edge-to-edge: the window draws behind the status and
        // navigation bars, and without this the QML settings gear sits under the clock.
        // The QML view is padded away from the bars via a wrapper whose background matches
        // the QML root color, so the bar areas read as part of the scene instead of as a
        // differently-coloured strip.
        val container = FrameLayout(this).apply {
            setBackgroundColor(QML_BACKGROUND) // keep in sync with Main.qml root color
            addView(
                qtQuickView,
                ViewGroup.LayoutParams(
                    ViewGroup.LayoutParams.MATCH_PARENT,
                    ViewGroup.LayoutParams.MATCH_PARENT,
                ),
            )
        }
        ViewCompat.setOnApplyWindowInsetsListener(container) { v, insets ->
            val bars = insets.getInsets(
                WindowInsetsCompat.Type.systemBars() or WindowInsetsCompat.Type.displayCutout()
            )
            v.setPadding(bars.left, bars.top, bars.right, bars.bottom)
            WindowInsetsCompat.CONSUMED
        }
        // The scene is dark regardless of the system theme, so the bar icons must be light
        // regardless of the system theme too.
        WindowInsetsControllerCompat(window, window.decorView).apply {
            isAppearanceLightStatusBars = false
            isAppearanceLightNavigationBars = false
        }

        setContentView(
            container,
            ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT,
            ),
        )

        mainQml.setStatusChangeListener(this)
        qtQuickView.loadContent(mainQml)

        // Kotlin -> QML: push every state change into the QML property.
        GateRepository.gateState
            .onEach { if (qmlReady) mainQml.gateState = it.state }
            .launchIn(lifecycleScope)

        GateRepository.bridgeStatus
            .onEach { if (qmlReady) mainQml.bridgeStatus = it.name.lowercase() }
            .launchIn(lifecycleScope)

        // Our own connection, which until now the phone UI had no way to mention: a broker
        // that rejected the password and a broker with nothing retained on it both rendered
        // as "Gate: unknown" and no error at all.
        GateRepository.connection
            .onEach {
                if (qmlReady) {
                    mainQml.connectionStatus = it.status.name.lowercase()
                    mainQml.connectionReason = it.reason
                }
            }
            .launchIn(lifecycleScope)

        // Why the last command did not reach the gate. Distinct from connectionReason: the
        // socket can be perfectly healthy and the command still be refused by the bridge.
        GateRepository.lastError
            .onEach { if (qmlReady) mainQml.lastError = it }
            .launchIn(lifecycleScope)

        // A new still: persist it and hand QML a fresh URL. A Bitmap cannot cross the
        // QtQuickView property bridge, so the frame travels as a file the Image loads.
        cameraGrabber.frame
            .onEach { bitmap -> if (qmlReady && bitmap != null) mainQml.cameraFrame = writeFrame(bitmap) }
            .launchIn(lifecycleScope)

        cameraGrabber.status
            .onEach { if (qmlReady) mainQml.cameraStatus = it.name.lowercase() }
            .launchIn(lifecycleScope)

        // Whether a camera URL is set at all decides if the QML panel appears. Driven off
        // config so toggling the URL in Settings shows/hides it without a relaunch.
        ConfigStore.config
            .onEach { if (qmlReady) mainQml.cameraConfigured = cameraPanelVisible(it.camera.isConfigured) }
            .launchIn(lifecycleScope)

        GateNotifier.observe(this, lifecycleScope)

        // First run goes straight to setup — but only from onStatusChanged, once the QML
        // reports READY. Launching Settings here would race the QML load: if Settings
        // covers this activity before the load completes, QtQuickView stalls mid-load and
        // never recovers, and backing out of Settings lands on a dead screen (see
        // docs/10-troubleshooting.md, blank-screen entry).
        firstRun = savedInstanceState == null
    }

    override fun onStart() {
        super.onStart()
        GateRepository.connect()
        cameraGrabber.start()
        // Settings may have changed while we were away — including the home position or
        // the geofence toggle.
        GeofenceManager.sync(this)
        maybeRequestNotifications()
    }

    override fun onStop() {
        GateRepository.disconnect()
        cameraGrabber.stop()
        super.onStop()
    }

    override fun onStatusChanged(status: QtQmlStatus?, content: QtQuickViewContent?) {
        Log.i(TAG, "QtQuickView status: $status")
        if (status != QtQmlStatus.READY || content != mainQml) return
        qmlReady = true

        // Seed the view with the state we already have.
        mainQml.gateState = GateRepository.gateState.value.state
        mainQml.bridgeStatus = GateRepository.bridgeStatus.value.name.lowercase()
        mainQml.connectionStatus = GateRepository.connection.value.status.name.lowercase()
        mainQml.connectionReason = GateRepository.connection.value.reason
        mainQml.lastError = GateRepository.lastError.value
        mainQml.cameraConfigured = cameraPanelVisible(ConfigStore.current.camera.isConfigured)
        mainQml.cameraStatus = cameraGrabber.status.value.name.lowercase()
        cameraGrabber.frame.value?.let { mainQml.cameraFrame = writeFrame(it) }

        // QML -> Kotlin: the generated connect<Signal>Listener returns an id you can use
        // to disconnect later. The first lambda argument is the signal name.
        commandListenerId = mainQml.connectCommandRequestedListener { _, action ->
            Log.i(TAG, "QML asked: $action")
            GateRepository.sendCommand(action)
        }

        // The theme is NoActionBar so the QML fills the screen; the way back into setup is
        // a control inside the QML itself rather than an options menu that cannot render.
        settingsListenerId = mainQml.connectSettingsRequestedListener { _, _ ->
            startActivity(Intent(this, SettingsActivity::class.java))
        }

        // The first-run setup redirect, deferred here from onCreate: the scene is loaded
        // now, so covering the activity can no longer strand the load. Cleared so a
        // re-emitted READY cannot re-open Settings over whatever the user is doing.
        if (firstRun && !ConfigStore.current.isComplete) {
            firstRun = false
            startActivity(Intent(this, SettingsActivity::class.java))
        }
    }

    /**
     * Writes the latest frame to a private cache file and returns a `file://` URL for QML.
     * The `?v=` query changes every call so the URL differs each time — setting an
     * identical string on a QML property emits no change, and QtQuick caches Image sources
     * by URL, so without it a new frame would never repaint. The bitmap is already ≤640 px
     * (downscaled in the grabber), so the JPEG is a few KB.
     */
    private fun writeFrame(bitmap: Bitmap): String {
        val file = File(cacheDir, "camera-frame.jpg")
        file.outputStream().use { bitmap.compress(Bitmap.CompressFormat.JPEG, 85, it) }
        return "file://${file.absolutePath}?v=${++frameVersion}"
    }

    /**
     * A configured RTSP URL is not enough to show the panel while the grabber is switched
     * off — it would sit on "Connecting…" forever, waiting for a frame nothing will send.
     * With this false the QML Column collapses the panel and the layout is exactly what it
     * was before the camera existed. See [CameraFrameGrabber.ENABLED].
     */
    private fun cameraPanelVisible(configured: Boolean) = configured && CameraFrameGrabber.ENABLED

    private fun granted(permission: String) =
        ContextCompat.checkSelfPermission(this, permission) == PackageManager.PERMISSION_GRANTED

    /**
     * Notifications only. Location is *not* requested here.
     *
     * The geofence is an opt-in feature now, so asking for location on first launch would
     * be asking for a permission the user has not asked for a feature for — which is both
     * rude and, per Play's location policy, a documented rejection reason. It is requested
     * from [requestLocationForGeofence], reached only by switching the feature on.
     */
    private fun maybeRequestNotifications() {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.TIRAMISU) return
        if (granted(Manifest.permission.POST_NOTIFICATIONS)) return
        // Once per install: a third-party app can bounce this activity in a loop, and a
        // permission dialog on every onStart would be a nuisance vector.
        if (askedForNotifications) return
        askedForNotifications = true
        requestPermissions(arrayOf(Manifest.permission.POST_NOTIFICATIONS), REQ_NOTIFICATIONS)
    }

    private companion object {
        const val TAG = "Domofon"
        const val REQ_NOTIFICATIONS = 3

        /** Main.qml's root `color: "#1e1e2e"`. Change one and you must change both. */
        val QML_BACKGROUND = 0xFF1E1E2E.toInt()

        /** Process-scoped: enough to stop a start-activity loop nagging the user. */
        var askedForNotifications = false
    }
}
